<?php
require_once(__DIR__.'/ProfessorService.php');
require_once(__DIR__.'/CategoriaService.php');
require_once(__DIR__.'/TipoService.php');
require_once(__DIR__.'/MultiplicadorService.php');
require_once(__DIR__.'/AtividadeService.php');
require_once(__DIR__.'/ComprovanteService.php');
#require_once(__DIR__.'/SecureService.php');
#require_once(__DIR__.'/SessionService.php');
require_once(__DIR__.'/../model/ManipuladorArquivos.php');
?>